config/routes.rb
Rails.application.routes.draw do
  root to: 'barbecues#index'
  resources :barbecues do
    resources :bookings, only: [:new, :create, :edit, :update]
  end
  devise_for :users do
  end

  resources :bookings, only: [:index, :show, :destroy]
  resources :users
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barbecue.rb
class Barbecue < ApplicationRecord
  has_one_attached :picture
  belongs_to :user
  has_many :bookings

  validates :barbecue_model, presence: true
  validates :barbecue_type, presence: true
  validates :barbecue_price, presence: true, numericality: { only_integer: true }
  validates :barbecue_description, length: { maximum: 250 }
  validates :barbecue_location, presence: true

  geocoded_by :barbecue_location
  after_validation :geocode, if: :will_save_change_to_barbecue_location?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :barbecue
  belongs_to :user

  validates :date_in, presence: true
  validates :date_out, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :barbecues
  has_many :bookings

  validates :email, presence: true
  validates :encrypted_password, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, only: :bookings
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/barbecues_controller.rb
class BarbecuesController < ApplicationController
  before_action :set_barbecue, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @barbecues = Barbecue.all
    @search = params["search"]
    if @search.present?
      @model = @search["barbecue_model"]
      @barbecues = Barbecue.where(barbecue_model: @model)
    end

    @markers = @barbecues.geocoded.map do |barbecue|
      {
        lat: barbecue.latitude,
        lng: barbecue.longitude,
        info_window: render_to_string(partial: "info_window", locals: { barbecue: barbecue }),
        image_url: helpers.asset_url("barbecrew2.png")
      }
    end
  end

  def show
    @markers = [
      {
        lat: @barbecue.latitude,
        lng: @barbecue.longitude,
        info_window: render_to_string(partial: "info_window", locals: { barbecue: @barbecue }),
        image_url: helpers.asset_url("barbecrew2.png")
      }
    ]

  end

  def new
    @barbecue = Barbecue.new
  end

  def create
    @barbecue = Barbecue.new(barbecue_params)
    @user = current_user
    @barbecue.user = @user
    if @barbecue.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @barbecue.update(barbecue_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @barbecue.destroy
    redirect_to user_path(current_user)
  end

  private

  def barbecue_params
    params.require(:barbecue).permit(:barbecue_model, :barbecue_type, :barbecue_price, :barbecue_description, :barbecue_location, :picture, :user_id)
  end

  def set_barbecue
    @barbecue = Barbecue.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_barbecue, only: [:show, :edit, :update, :destroy]

  def index
    #Bookings que EU FIZ
    @bookings = Booking.where(user: current_user)
    #Bookings que fizeram das minhas churrasqueiras
    @booked = Booking.where(barbecues: { user: current_user }).joins(:barbecue)
  end

  def show
  end

  def new
    @booking = Booking.new
    @barbecue = Barbecue.find(params[:barbecue_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.barbecue = Barbecue.find(params[:barbecue_id])
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: 'The booking was successfully deleted.'
  end

  private

  def booking_params
    params.require(:booking).permit(:date_in, :date_out)
  end

  def set_barbecue
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  def profile
    @user = current_user
  end

  # GET /trainers
  def index
    @user = User.all
  end

  # GET /trainers/1
  def show
    @user = current_user
  end

  def show
    @user = current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/barbecues/_form.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-4">
    <div class="flat-form2">
      <%= simple_form_for(barbecue) do |f| %>
       <div class="flat-form2">
       <%= f.label :Model %>
        <%= f.input :barbecue_model, label: false, placeholder: "Type in the barbecue's model", :input_html => { class: "form-nice-class" } %>
        </div>
         <div class="flat-form2">
         <%= f.label :Type %>
        <%= f.input :barbecue_type, label: false, placeholder: "Electric, Gas, Charcoal, etc..", :input_html => { class: "form-nice-class" } %>
        </div>
         <div class="flat-form2">
         <%= f.label :Price %>
        <%= f.input :barbecue_price, as: :string , label: false, placeholder: "What is the daily rate?", :input_html => { class: "form-nice-class" } %>
        </div>
         <div class="flat-form2">
         <%= f.label :Description %>
        <%= f.input :barbecue_description, label: false, placeholder: "Type a short and objective description", :input_html => { class: "form-nice-class" } %>
        </div>
         <div class="flat-form2">
         <%= f.label :Location %>
        <%= f.input :barbecue_location, label: false, placeholder: "Type in the adress?", :input_html => { class: "form-nice-class" } %>
        </div>
         <div class="flat-form2">

         <%= f.label :picture %>
         <%= f.input :picture, as: :file, label: false %>

        </div>
         <div class="flat-form2">
        <%= f.submit 'Add a Barbecue', class: 'btn btn-success btn-block w-100 p-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/barbecues/_header.html.erb
<div class="banner-container">

    <div class="row">
        <div class="col-xs-12">
            <div><h1 class="banner-title">Welcome to Barbecrew</h1></div>
        
                <div class= "search-bar">

                    <svg xmlns="http://www.w3.org/2000/svg" style="display:none">
                    <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-search-22" viewBox="0 0 40 40">
                        <path d="M24.382 25.485c-1.704 1.413-3.898 2.263-6.292 2.263-5.42 0-9.814-4.36-9.814-9.736 0-5.377 4.394-9.736 9.814-9.736s9.815 4.36 9.815 9.736c0 2.126-.687 4.093-1.853 5.694l5.672 5.627-1.73 1.718-5.612-5.565zM20 40c11.046 0 20-8.954 20-20S31.046 0 20 0 0 8.954 0 20s8.954 20 20 20zm-1.91-14.686c4.065 0 7.36-3.27 7.36-7.302 0-4.033-3.295-7.302-7.36-7.302s-7.36 3.27-7.36 7.302c0 4.033 3.295 7.302 7.36 7.302z"
                        fill-rule="evenodd" />
                    </symbol>
                    <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-clear-5" viewBox="0 0 20 20">
                        <path d="M10 20c5.523 0 10-4.477 10-10S15.523 0 10 0 0 4.477 0 10s4.477 10 10 10zm1.35-10.123l3.567 3.568-1.225 1.226-3.57-3.568-3.567 3.57-1.226-1.227 3.568-3.568-3.57-3.57 1.227-1.224 3.568 3.568 3.57-3.567 1.224 1.225-3.568 3.57zM10 18.272c4.568 0 8.272-3.704 8.272-8.272S14.568 1.728 10 1.728 1.728 5.432 1.728 10 5.432 18.272 10 18.272z"
                        fill-rule="evenodd" />
                    </symbol>
                    </svg>

                    <form novalidate="novalidate" onsubmit="return false;" class="searchbox sbx-custom">
                    <div role="search" class="sbx-custom__wrapper">
                        <input type="search" name="search" placeholder="Search your barbecue" autocomplete="off" required="required" class="sbx-custom__input">
                        <button type="submit" title="Submit your search query." class="sbx-custom__submit">
                        <svg role="img" aria-label="Search">
                            <use xlink:href="#sbx-icon-search-22"></use>
                        </svg>
                        </button>
                        <button type="reset" title="Clear the search query." class="sbx-custom__reset">
                        <svg role="img" aria-label="Reset">
                            <use xlink:href="#sbx-icon-clear-5"></use>
                        </svg>
                        </button>
                    </div>
                    </form>
                    <script type="text/javascript">
                    document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
                    </script>

                </div>
        </div>
    </div>
</div>

app/views/barbecues/_info_window.html.erb
<h5><%= barbecue.barbecue_model %></h5>
<p>€<%= barbecue.barbecue_price %></p>

app/views/barbecues/edit.html.erb
<div class="row justify-content-center d-flex justify-content-around align-self-center p-1">
  <div class="col-4">
    <h4 class="row justify-content-center">Edit this Barbegrill: </h4>
  </div>
</div>

<div class="row justify-content-center d-flex justify-content-around align-self-center">
  <%= render 'form', barbecue: @barbecue %>
</div>

<div class="row justify-content-center p-2">
  <div class="col-4  d-flex justify-content-between align-self-center p-1">
    <%=  link_to 'Home page', root_path, class: 'btn btn-outline-success btn-block w-40'%>
    <%= link_to 'Back', :back, class: 'btn btn-outline-success btn-block w-40'%>
  </div>
</div>

app/views/barbecues/index.html.erb
<div>
    <div><%= render 'header' %>
    </div>

<div class="barbecue-title mt-3">
  <div class="row">
    <div class="col-12">
      <h3>Search a barbecue for rent</h3>

            <div class="container">

            <div class="flat-card-map">
                <div class="col-md-12 mt-3">
                    <div style="width: 98%; height: 350px; margin-left: 12px;"
                        data-controller="mapbox"
                        data-mapbox-markers-value="<%= @markers.to_json %>"
                        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
                    </div>
                </div>
            </div>
                
                <div class="row">
                    <% @barbecues.each do |barbecue| %>
                    <div class="col-md-4">
                        <div class="flat-card">
                        <div class="flat-card-image" style="background-image: url('<%= barbecue.picture.key.present? ? cl_image_path(barbecue.picture.key) : '' %>')"></div>
                        <div class="flat-card-content">
                            <div class="flat-card-title">
                            <h5><%= barbecue.barbecue_model %></h5>
                            </div>
                            <h6><%= barbecue.barbecue_description %></h6>
                            <h6>€<%= barbecue.barbecue_price %></h6>
                        
                        </div>
                        <div class="flat-card-actions">
                        <div class="btn-group btn-sm" role="group" aria-label="Button group">
                            <%= link_to 'More info', barbecue_path(barbecue), class: "btn btn-outline-dark btn-sm" %>
                        </div>
                        </div>
                        </div>
                    </div>
                    <% end %>

                </div>
            </div>
    </div>
  </div>
</div>

app/views/barbecues/new.html.erb
<div class="row justify-content-center d-flex justify-content-around align-self-center p-1">
  <div class="col-4">
    <h4>Add a new Barbecue for renting!</h4>
  </div>
</div>

<div class="row justify-content-center d-flex justify-content-around align-self-center">
  <%= render 'form', barbecue: @barbecue %>
</div>

<div class="row justify-content-center p-2">
  <div class="col-4  d-flex justify-content-between align-self-center p-1">
    <%=  link_to 'See the Barbecue', @barbecue, class: 'btn btn-outline-dark btn-block w-40 btn-sm'%>
    <%= link_to 'Back', :back, class: 'btn btn-outline-dark btn-block w-40 btn-sm'%>
  </div>
</div>

app/views/barbecues/show.html.erb
<div class="map" style="background-image: url('<%= @barbecue.picture.key.present? ? cl_image_path(@barbecue.picture.key) : '' %>')"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h3><%= @barbecue.barbecue_model %></h3>
        <p class="flat-show-address"><%= @barbecue.barbecue_description %></p>
      </div>

        <h3>Your barbecue location</h3>

                    <div class="flat-card-map">
                        <div class="col-md-12 mt-3">
                            <div style="width: 98%; height: 340px; margin-left: 9px;"
                                data-controller="mapbox"
                                data-mapbox-markers-value="<%= @markers.to_json %>"
                                data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
                            </div>
                        </div>
                    </div>

        <div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @barbecue.barbecue_description %>&zoom=13&scale=2&size=1000x1000&maptype=roadmap&markers=color:red%7C<%= @barbecue.barbecue_description %>&key=AIzaSyBtaHK-BLhBg7TruJu8iKk_wETqZMJM-GY')"></div>
      </div>


    <div class="col-4">
      <div class="flat-show-card">

        <%= link_to "Book this Barbecue", new_barbecue_booking_path(@barbecue), class: 'btn btn-success mt-3 form-nice-class' %>

      </div>
      <div class="flat-show-card">
        <h4>Price/day</h4>
        <div class="flex">
        
          <div class="flex ms-3">
            <i class="material-icons me-2">€</i> <%= @barbecue.barbecue_price %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share with your friends</h6>

          <div class="flex">
            <i class="fa fa-facebook-square fa-2x me-2"></i>
            <i class="fa fa-twitter-square fa-2x me-2"></i>
            <i class="fa fa-pinterest-square fa-2x me-2"></i>
            <i class="fa fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-4">
    <div class="flat-form2">
      <%= simple_form_for [@barbecue, @booking] do |f| %>
       <div class="flat-form2">
       <%= f.label :Date_in %>
        <%= f.input :date_in, label: false, placeholder: "Date in", :input_html => { class: "form-nice-class" } %>
        </div>
         <div class="flat-form2">
         <%= f.label :Date_out %>
        <%= f.input :date_out, label: false, placeholder: "Date out", :input_html => { class: "form-nice-class" } %>
         <div class="flat-form2">
        <%= f.submit 'Booking the Barbecue', class: 'btn btn-success btn-block w-100 p-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h3 class="mt-3 mb-4 text-center">The ones I've booked</h3>

<div class="container">

    <div class="row">
        <% @bookings.each do |booking| %>
            <div class="col-md-2">
                <div class="flat-card3">
                    <div class="flat-card-image" style="background-image: url('<%= booking.barbecue.picture.key.present? ? cl_image_path(booking.barbecue.picture.key) : '' %>')"></div>
                    <div class="flat-card-content2">
                        <div class="flat-card-title">
                        
                            <h6><%= booking.barbecue.barbecue_model %></h6>
                            <p>Date in: <%= booking.date_in %></p>
                            <p>Date out: <%= booking.date_out %></p>
                        </div>
                        <div class="flat-card-actions">
                        <div class="btn-group btn-sm" role="group" aria-label="Button group">
                            <%= link_to 'Delete', booking_path(booking), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm" %>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>




<h3 class="mt-3 mb-4 text-center">My Barbecue's bookings</h3>

<div class="container">
    <div class="row">
        <% @booked.each do |booking| %>
            <div class="col-md-2">
                <div class="flat-card3">
                    <div class="flat-card-image" style="background-image: url('<%= booking.barbecue.picture.key.present? ? cl_image_path(booking.barbecue.picture.key) : '' %>')"></div>
                    <div class="flat-card-content2">

                            <h6><%= booking.barbecue.barbecue_model %></h6>
                            <p>Date in: <%= booking.date_in %></p>
                            <p>Date out: <%= booking.date_out %></p>

                        <div class="flat-card-actions">
                        <div class="btn-group btn-sm" role="group" aria-label="Button group">
                            <%= link_to 'Delete', booking_path(booking), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm" %>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/bookings/new.html.erb
<div class="row justify-content-center d-flex justify-content-around align-self-center p-1">
  <div class="col-4">
    <h4>booking the barbecue!</h4>
  </div>
</div>

<div class="row justify-content-center d-flex justify-content-around align-self-center">
  <%= render 'form', booking: @booking %>
</div>

<div class="row justify-content-center p-2">
  <div class="col-4  d-flex justify-content-between align-self-center p-1">
    <%=  link_to 'See the Bookings', @booking, class: 'btn btn-outline-dark btn-block w-40 btn-sm'%>
    <%= link_to 'Go Back to Home page', root_path, class: 'btn btn-outline-dark btn-block w-40 btn-sm'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barbecrew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>YES! WE HAVE HOME PAGE</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "barbecrew2.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My barbecues", user_path(current_user), class: "nav-link ml-5" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "imguser.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
              <%= link_to "Create Offer", new_barbecue_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_header.html.erb
<div class="banner-container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 offset-sm-2">
            <h1 class="banner-title">Welcome to Barbecrew</h1>

            <%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
            <%= f.input :Seach_for_a_barbecue_model, input_html: {value: ""} %>   
            <%= f.submit "Search", class: "btn btn-primary border-bottom" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<h3 class="mt-3 mb-4 text-center">My Barbecues</h3>

<div class="container">

    <div class="row">
        <% @user.barbecues.each do |barbecue| %>
            <div class="col-md-2">
                <div class="flat-card2">
                    <div class="flat-card-image" style="background-image: url('<%= barbecue.picture.key.present? ? cl_image_path(barbecue.picture.key) : '' %>')"></div>
                    <div class="flat-card-content">
                        <div class="flat-card-title">
                        
                            <h6><%= barbecue.barbecue_model %></h6>
                            <p><%= barbecue.barbecue_description %></p>
                        </div>
                            <div class="flat-card-actions">
                              <div class="btn-group btn-sm form-nice-class" role="group" aria-label="Button group">
                                <%= link_to 'Edit', edit_barbecue_path(barbecue), class: "btn btn-outline-primary btn-sm" %>
                              </div>
                              <div class="btn-group btn-sm form-nice-class" role="group" aria-label="Button group">
                                <%= link_to 'Delete', barbecue_path(barbecue), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm" %>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>